import { TNewsArticle } from "../types/api-response";

// these are used for testing purposes
export const mockArticles:TNewsArticle[] = [
  {
    title: "Hello world",
    description: "This is a description",
    url: "https://example.com", 
    publishedAt: new Date("2023-01-01T00:00:00.000Z").toISOString(), 
    urlToImage: "https://example.com/image.jpg", 
    source: { name: "Example", id: "https://example.com" }, 
    author: "John Doe", 
    content: null,
  },
  {
    title: "Hello world", 
    description: "This is a description", 
    url: "https://example.com", 
    publishedAt: new Date("2023-01-01T00:00:00.000Z").toISOString(), 
    urlToImage: "https://example.com/image.jpg", 
    source: { name: "Example", id: "https://example.com" }, 
    author: "John Doe", 
    content: null,  
  },
  {
    title: "Hello world", 
    description: "This is a description", 
    url: "https://example.com", 
    publishedAt: new Date("2023-01-01T00:00:00.000Z").toISOString(), 
    urlToImage: "https://example.com/image.jpg", 
    source: { name: "Example", id: "https://example.com" }, 
    author: "John Doe", 
    content: null,
  },
  {
    title: "Hello world",
    description: "This is a description",
    url: "https://example.com", 
    publishedAt: new Date("2023-01-01T00:00:00.000Z").toISOString(), 
    urlToImage: "https://example.com/image.jpg", 
    source: { name: "Example", id: "https://example.com" }, 
    author: "John Doe", 
    content: null,
  },
  {
    title: "Hello world", 
    description: "This is a description", 
    url: "https://example.com", 
    publishedAt: new Date("2023-01-01T00:00:00.000Z").toISOString(), 
    urlToImage: "https://example.com/image.jpg", 
    source: { name: "Example", id: "https://example.com" }, 
    author: "John Doe", 
    content: null,  
  },
  {
    title: "Hello world", 
    description: "This is a description", 
    url: "https://example.com", 
    publishedAt: new Date("2023-01-01T00:00:00.000Z").toISOString(), 
    urlToImage: "https://example.com/image.jpg", 
    source: { name: "Example", id: "https://example.com" }, 
    author: "John Doe", 
    content: null,
  },
  {
    title: "Hello world",
    description: "This is a description",
    url: "https://example.com", 
    publishedAt: new Date("2023-01-01T00:00:00.000Z").toISOString(), 
    urlToImage: "https://example.com/image.jpg", 
    source: { name: "Example", id: "https://example.com" }, 
    author: "John Doe", 
    content: null,
  },
  {
    title: "Hello world", 
    description: "This is a description", 
    url: "https://example.com", 
    publishedAt: new Date("2023-01-01T00:00:00.000Z").toISOString(), 
    urlToImage: "https://example.com/image.jpg", 
    source: { name: "Example", id: "https://example.com" }, 
    author: "John Doe", 
    content: null,  
  },
  {
    title: "Hello world", 
    description: "This is a description", 
    url: "https://example.com", 
    publishedAt: new Date("2023-01-01T00:00:00.000Z").toISOString(), 
    urlToImage: "https://example.com/image.jpg", 
    source: { name: "Example", id: "https://example.com" }, 
    author: "John Doe", 
    content: null,
  }
]